var baseAPIUrl = 'https://admin.barikoi.xyz/v1/'
export const API_URL = 'https://user-authentication-api.now.sh/api';
export const AUTH_URI = baseAPIUrl+'auth/login/';
export const AUTH_REG = baseAPIUrl+'auth/register/';
export const AUTH_BUS = baseAPIUrl+'business/register/';
export const AUTH_LOGI = baseAPIUrl+'business/register/';
export const FEED_BACK = baseAPIUrl+'connect/us/';
export const USER_PROF = baseAPIUrl+'auth/user';
export const DEV_API_KEY = baseAPIUrl+'auth/business/CurrentActiveKey';
export const KEY_GEN = baseAPIUrl+'auth/business/keygen/';
export const UPDATE_PASSWORD = baseAPIUrl+'auth/UpdatePass';
export const API_ANALYTCS = baseAPIUrl+'developer/analytics';
export const RESET_PASSWORD = 'https://admin.barikoi.xyz/v1/auth/password/reset'